---
# setup instance Alertmanager
- hosts: alert_rule_app
  become: yes
  become_user: root
  roles:
    - { role: openshift_monitoring/deploy_rules_app}
    
# setup instance Alertmanager
- hosts: alert_rule_sys
  become: yes
  become_user: root
  roles:
    - { role: openshift_monitoring/deploy_rules_sys_app}