---

- hosts: all
  become: yes
  tasks:
    - name: Restart server
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true
      tags:
        - reboot_server

    - name: Delay for reboot
      pause:
        minutes: 2
      delegate_to: localhost
      tags:
        - reboot_server

    - name: waiting for reboot server
      wait_for:
        host: "{{ inventory_hostname }}"
        # search_regex: OpenSSH
        connect_timeout: 5
        port: 22
        sleep: 10
        delay: 30
        timeout: 180
      become: false
      ignore_errors: yes
      delegate_to: localhost
      tags:
        - reboot_server
