---
# setup instance prometheus system data

- hosts: instance-prometheus_app_data
  become: yes
  become_user: root
  vars:
    homedir: /etc/prometheus
    prometheus_job: "app_data"
    service_option: setup
  roles:
    - { role: openshift_monitoring/prometheus-service , action: 'app_data' }