groups:
- name: default
  rules:
  - alert: federate_down
    expr: up{job='federate_app_aggregate'} == 0
    annotations:
      summary: "Promtheus Federate has down"
      description: "{{$labels.instance}} agent down"
