---
- name: 'REMOVE HOMEDIR'
  file:
    dest: "{{vars.homedir}}/targets"
    state: absent

- name: 'CRATE HOMEDIR TARGETS'
  file:
    path: "{{vars.homedir}}/targets"
    state: directory
    owner: prometheus
    group: prometheus
    
- name: 'Prometheus Config Main: {{vars.prometheus_type}}'
  template:
    src: "cen_aggregate/prometheus.j2"
    dest: "{{vars.homedir}}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: 0644

- name: 'Prometheus Config Options: {{vars.prometheus_type}}'
  copy: 
    src: "files/cen_aggregate/prometheus.opt" 
    dest: "/etc/default/prometheus"
    owner: prometheus
    group: prometheus
    mode: 0755
    
- name: 'INIT VAR ARRAY INSTANCE'
  set_fact:
    mycfg1: []
    mycfg2: []
    mycfg3: []

- name: 'SET TARGET ARRAY FOR node_exporter'
  set_fact:
    mycfg1: '{{mycfg1}} + [ {"targets":["{{hostvars[item].inventory_hostname}}:{{hostvars[item].port_node}}"],"labels":{"instance_hostname":"{{hostvars[item].instance_hostname}}","instance_group":"{{hostvars[item].instance_group}}"}} ]'
  with_items: "{{groups['promcfg-targets-node_exporter']}}"

- name: 'SET TARGET ARRAY FOR elasticsearch'
  set_fact:
    mycfg2: '{{mycfg2}} + [ {"targets":["{{hostvars[item].inventory_hostname}}:{{vars.vars.targets["els"].port}}"],"labels":{"instance_hostname":"{{hostvars[item].instance_hostname}}"}} ]'
  with_items: "{{groups['instance-elasticsearch']}}"

- name: 'SET TARGET ARRAY FOR nodefc_exporter'
  set_fact:
    mycfg3: '{{mycfg3}} + [ {"targets":["{{hostvars[item].inventory_hostname}}:9150"],"labels":{"instance_hostname":"{{hostvars[item].instance_hostname}}"}} ]'
  with_items: "{{groups['instance-oracle']}}"
  
- name: 'DEPLOY PROMETHEUS TARGET FILE node_exporter'
  copy: 
    content: "{{ mycfg1 | to_json}}" 
    dest: "{{vars.homedir}}/targets/node_exporter.json"
    owner: prometheus
    group: prometheus
    mode: 0644

- name: 'DEPLOY PROMETHEUS TARGET FILE elasticsearch'
  copy: 
    content: "{{ mycfg2 | to_json}}" 
    dest: "{{vars.homedir}}/targets/elasticsearch.json"
    owner: prometheus
    group: prometheus
    mode: 0644

- name: 'DEPLOY PROMETHEUS TARGET FILE nodefc_exporter'
  copy: 
    content: "{{ mycfg3 | to_json}}" 
    dest: "{{vars.homedir}}/targets/nodefc_exporter.json"
    owner: prometheus
    group: prometheus
    mode: 0644
    
- name: 'RESTART SERVICE PROMETHEUS'
  #service:  name=prometheus state=reloaded
  uri:
    url: http://localhost:9090/-/reload
    method: POST