{% set addr = vars.groups['instance-prometheus_sys_aggregate'][0] %}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: prometheus
    nodePort: 30090 
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Route
metadata:
  name: prometheus-route
  namespace: monitoring
  labels:
    app: prometheus
    exposure: general
spec:
  host: "{{ vars.hostvars[addr].federate_host }}"
  port:
    targetPort: prometheus
  to:
    kind: Service
    name: prometheus-service
  tls:
    termination: edge