---
Service_Group:
  - { APP_SCOPE: 'equator', SVC_GROUP: 'cicd', ENV: '', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'cicd', ENV: '', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'cicd', ENV: '', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'dataplatform', ENV: 'dev', CPU: '3000', MEMMORY: '6Gi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'dataplatform', ENV: 'performance', CPU: '5000', MEMMORY: '8Gi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'dataplatform', ENV: 'qa', CPU: '3000', MEMMORY: '6Gi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'dataplatform', ENV: 'staging', CPU: '3000', MEMMORY: '6Gi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'dataplatform', ENV: '', CPU: '3000', MEMMORY: '6Gi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'default', ENV: 'dev', CPU: '22000', MEMMORY: '102400Mi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'default', ENV: 'performance', CPU: '29000', MEMMORY: '161Gi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'default', ENV: 'qa', CPU: '22000', MEMMORY: '102400Mi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'default', ENV: 'staging', CPU: '22000', MEMMORY: '102400Mi' }
  - { APP_SCOPE: 'equator', SVC_GROUP: 'sandbox', ENV: 'dev', CPU: '17000', MEMMORY: '97Gi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'creditpay', ENV: 'dev', CPU: '8192', MEMMORY: '12Gi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'creditpay', ENV: 'performance', CPU: '12000', MEMMORY: '26000Mi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'creditpay', ENV: 'qa', CPU: '2800', MEMMORY: '6000Mi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'creditpay', ENV: 'staging', CPU: '2800', MEMMORY: '6000Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'asset', ENV: 'dev', CPU: '4096', MEMMORY: '8Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'asset', ENV: 'performance', CPU: '6144', MEMMORY: '12Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'asset', ENV: 'qa', CPU: '2048', MEMMORY: '4Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'asset', ENV: 'staging', CPU: '2048', MEMMORY: '4Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'bill-payment', ENV: 'dev', CPU: '87100', MEMMORY: '90522Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'bill-payment', ENV: 'performance', CPU: '143000', MEMMORY: '237619Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'bill-payment', ENV: 'qa', CPU: '41600', MEMMORY: '77875Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'bill-payment', ENV: 'staging', CPU: '41600', MEMMORY: '77875Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'core', ENV: 'dev', CPU: '27000', MEMMORY: '65Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'core', ENV: 'performance', CPU: '109000', MEMMORY: '262Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'core', ENV: 'qa', CPU: '27000', MEMMORY: '65Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'core', ENV: 'staging', CPU: '27000', MEMMORY: '65Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'dataplatform', ENV: 'dev', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'dataplatform', ENV: 'performance', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'dataplatform', ENV: 'qa', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'dataplatform', ENV: 'staging', CPU: '4000', MEMMORY: '15Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'default', ENV: 'dev', CPU: '12000', MEMMORY: '12Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'default', ENV: 'performance', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'default', ENV: 'qa', CPU: '', MEMMORY: '' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'default', ENV: 'staging', CPU: '4000', MEMMORY: '15Gi' } 
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'monitoring', ENV: 'dev', CPU: '4000', MEMMORY: '8Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'monitoring', ENV: 'performance', CPU: '6000', MEMMORY: '12Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'monitoring', ENV: 'qa', CPU: '4000', MEMMORY: '8Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'monitoring', ENV: 'staging', CPU: '4000', MEMMORY: '8Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'monitoring', ENV: '', CPU: '1000', MEMMORY: '4Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'product', ENV: 'dev', CPU: '22000', MEMMORY: '20000Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'product', ENV: 'performance', CPU: '34000', MEMMORY: '43000Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'product', ENV: 'qa', CPU: '17000', MEMMORY: '17000Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'product', ENV: 'staging', CPU: '17000', MEMMORY: '17000Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'sandbox', ENV: 'dev', CPU: '1600', MEMMORY: '64Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'sof', ENV: 'dev', CPU: '6500', MEMMORY: '26Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'sof', ENV: 'performance', CPU: '11700', MEMMORY: '47924Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'sof', ENV: 'qa', CPU: '5200', MEMMORY: '21300Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'sof', ENV: 'staging', CPU: '5200', MEMMORY: '21300Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'tmx', ENV: 'dev', CPU: '51000', MEMMORY: '54580Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'tmx', ENV: 'performance', CPU: '24000', MEMMORY: '34612Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'tmx', ENV: 'qa', CPU: '10000', MEMMORY: '11981Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'tmx', ENV: 'staging', CPU: '10000', MEMMORY: '11981Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'kiosk', ENV: 'dev', CPU: '54600', MEMMORY: '64Gi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'kiosk', ENV: 'qa', CPU: '13400', MEMMORY: '23961Mi' }
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'kiosk', ENV: 'performance', CPU: '17300', MEMMORY: '26Gi' } 
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'kiosk', ENV: 'staging', CPU: '13400', MEMMORY: '22Gi' }  
  - { APP_SCOPE: 'truemoney', SVC_GROUP: 'mock', ENV: 'performance', CPU: '36000', MEMMORY: '196608Mi' }  
  - { APP_SCOPE: 'nano', SVC_GROUP: 'common', ENV: 'dev', CPU: '800', MEMMORY: '1536Mi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'common', ENV: 'qa', CPU: '800', MEMMORY: '1536Mi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'common', ENV: 'staging', CPU: '800', MEMMORY: '1536Mi' }
  - { APP_SCOPE: 'nano', SVC_GROUP: 'common', ENV: 'performance', CPU: '800', MEMMORY: '1536Mi' }       
  - { APP_SCOPE: 'nano', SVC_GROUP: 'dataplatform', ENV: 'staging', CPU: '1000', MEMMORY: '2048Mi' }   