---
- name: 'git pull'
  raw: "cd /home/sysansible/acm-ocp-grafana/; git checkout {{orgName}}; git pull origin {{orgName}}"
  
- name: 'CRATE HOMEDIR DATA'
  file:
    path: "/home/sysansible/data"
    state: directory
    owner: sysansible
    group: sysansible
  
- name: 'COPY library to server'
  copy: 
    src: "files/sre_grafana_restore" 
    dest: "/home/sysansible/sre_grafana_restore"
    mode: "u+rwx"
    
- name: 'RUN Script Grafana'
  raw: "cd /home/sysansible/; ./sre_grafana_restore --target={{target}} --orgName={{orgName}} --handler=dashboard-backup --tokenkey={{tokenkey}}"
  
- name:  'copying data {{orgName}}'
  raw: "cp -r /home/sysansible/data/{{orgName}}/dashboard/*.json /home/sysansible/acm-ocp-grafana/{{orgName}}/dashboard/"
  
- name: 'git push'
  raw: "cd /home/sysansible/acm-ocp-grafana/;git add .; git commit -a -m {{orgName}}; git push origin {{orgName}}"
  
- name: 'Clean path data'
  file:
    state: absent
    path: "/home/sysansible/data"