apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: node-exporter
    spec:

      serviceAccount: default
      containers:
      - image: {{ image_node_exporter }}
        imagePullPolicy: Always
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape

        args:
          - --path.procfs
          - /host/proc
          - --path.sysfs
          - /host/sys
          - --collector.filesystem.ignored-mount-points
          - "^/(sys|proc|dev|host|etc|var/run|rootfs/dev|rootfs/proc|rootfs/run|rootfs/sys).*"

        volumeMounts:
          - name: dev
            mountPath: /host/dev
          - name: proc
            mountPath: /host/proc
          - name: sys
            mountPath: /host/sys
          - name: rootfs
            mountPath: /rootfs
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /